// Master melee skin list, derived from https://valorant.fandom.com/wiki/Melee (Store + Battle Pass tables)
// Each entry: collection (english), jp: array of japanese keyword aliases used to detect this collection/skin in JP video titles
// items: list of required "content units" -> {key, jp: [aliases]} ; base always required.

const COLOR_JP = {
  Red: ['レッド'], Blue: ['ブルー'], Black: ['ブラック'], White: ['ホワイト'], Purple: ['パープル'],
  Green: ['グリーン'], Yellow: ['イエロー'], Pink: ['ピンク'], Orange: ['オレンジ'], Silver: ['シルバー'],
  Gold: ['ゴールド'], Bronze: ['ブロンズ'], Obsidian: ['オブシディアン'], Teal: ['ティール'], Copper: ['コッパー'],
  Ivory: ['アイボリー'], Indigo: ['インディゴ'], Scarlet: ['スカーレット'], Ruby: ['ルビー'], Pearl: ['パール'],
  Venom: ['ヴェノム'], Cobalt: ['コバルト'], Living: ['リビング'], Eternal: ['エターナル'],
  'Deep Sea': ['ディープシー'], Desert: ['デザート'], Sea: ['シー'], Tundra: ['ツンドラ'],
  Dark: ['ダーク','ブラック'], Sunset: ['サンセット'], Dusk: ['ダスク'], Night: ['ナイト'],
  Kumo: ['クモ'], Hana: ['ハナ'], Tsubame: ['ツバメ'], CN: ['CN'], Pacific: ['Pacific','パシフィック'],
  Americas: ['Americas','アメリカズ'], EMEA: ['EMEA'], Ice: ['アイス'], Moss: ['モス'],
  Rainbow: ['レインボー'], 'Red Camo': ['レッド迷彩','レッドカモ'], 'Blue Camo': ['ブルー迷彩','ブルーカモ'],
  'Green Camo': ['グリーン迷彩','グリーンカモ'], 'Purple Shear': ['パープル'], Onyx: ['オニキス'],
  Bubblegum: ['バブルガム'], 'Dance Fever': ['ダンスフィーバー'], 'K.nock O.ut!!': ['K.nock O.ut'],
  Tan: ['タン'], Aquamarine: ['アクアマリン'], Grey: ['グレー','グレイ'],
};

// For compound names like "Blue/Purple" or "Green/Yellow/Black": accept the literal joined
// phrase OR any individual component color word, since the channel doesn't always spell out
// the full compound in the title.
function jpColor(name){
  if (COLOR_JP[name]) return COLOR_JP[name];
  if (name.includes('/')) {
    const parts = name.split('/');
    let out = [name];
    parts.forEach(p => { out = out.concat(COLOR_JP[p] || [p]); });
    return out;
  }
  return [name];
}

const STORE = [
{c:'5 Years // Beta Remastered', n:'5 Years // Beta Remastered Knife', jp:['5 YEARS','BETA','リマスター'], anim:true, variants:['Red','Purple','Blue']},
{c:'Abyssal', n:'Caeruleus', jp:['アビサル','セルリアス'], variants:[]},
{c:'Aemondir', n:'Blade of Aemondir', jp:['エイモンディア'], vfx:true, variants:['Silver','Bronze','Obsidian']},
{c:'Altitude', n:'Altitude Knuckle Knife', jp:['アルティチュード'], variants:[]},
{c:'Aperture', n:'Aperture Stiletto', jpOr:['アパッチャー','アパーチャー'], variants:[]},
{c:'Araxys', n:'Araxys Bio Harvester', jp:['アラクシス','バイオハーベスター'], anim:true, variants:['Purple','Black','Silver']},
{c:'Araxys', n:'Araxys Bio-Atomizers', jp:['アラクシス','バイオアトマイザー'], anim:true, variants:['Purple','Black','Silver']},
{c:'Arcane', n:'Arcane Gauntlets', jp:['ARCANE','ガントレット'], anim:true, variants:[]},
{c:'Ayakashi', n:'Kogitsune', jp:['コギツネ'], anim:true, variants:['Red','Pink','Blue']},
{c:'Black.Market', n:'Black.Market Butterfly Knife', jp:['ブラックマーケット'], anim:true, variants:[]},
{c:'Blackthorn', n:'Blackthorn Blades', jp:['ブラックソーンブレード'], anim:true, variants:['Gold','Blue','Purple Shear']},
{c:'BlastX', n:'BlastX Polymer KnifeTech Coated Knife', jp:['ブラストX'], anim:true, variants:['Black','Yellow','Pink']},
{c:'Bolt', n:'Bolt Knife', jp:['ボルトナイフ'], anim:true, variants:['Red','Black','White']},
{c:'Bubblegum Deathwish', n:'Bubblegum Deathwish Chainsaw', jp:['バブルガム デスウィッシュ'], anim:true, variants:['Yellow','Red','Purple']},
{c:'Celestial', n:'Celestial Fan', jp:['セレスティアル'], anim:true, variants:[]},
{c:'Champions 2021', n:'Champions 2021 Karambit', jpOr:['CHAMPIONS 2021','チャンピオンズ 2021'], vfx:true, aura:true, variants:[]},
{c:'Champions 2022', n:'Champions 2022 Butterfly Knife', jp:['CHAMPIONS 2022'], anim:true, aura:true, variants:[]},
{c:'Champions 2023', n:'Champions 2023 Kunai', jp:['CHAMPIONS 2023'], anim:true, aura:true, variants:[]},
{c:'Champions 2024', n:'Champions 2024 Blade', jp:['CHAMPIONS 2024'], anim:true, aura:true, variants:[]},
{c:'Champions 2025', n:'Champions 2025 Butterfly Knife', jp:['CHAMPIONS 2025'], anim:true, aura:true, variants:[]},
{c:'Chromedek', n:'Chromedek Gauntlet', jp:['クロムデック'], variants:[]},
{c:'ChronoVoid', n:'Terminus A Quo', jp:['クロノヴォイド','テルミヌス'], anim:true, variants:['Purple','Red','Black']},
{c:'Combat Crafts', n:'Combat Crafts Axe', jp:['コンバットクラフト'], anim:'Randomizer', variants:[]},
{c:'Crimsonbeast', n:'Crimsonbeast Hammer', jp:['クリムゾンビースト'], vfx:true, variants:[]},
{c:'Cryostasis', n:'Cryostasis Impact Drill', jp:['クライオステイシス'], vfx:true, variants:[]},
{c:'CYRAX', n:'CYRAX Fanblade', jp:['サイラックス'], anim:true, variants:['Red','Yellow','Purple']},
{c:'Daydreams', n:'Daydreams Crowbar', jp:['デイドリーム'], variants:[]},
{c:'Doombringer', n:'Doombringer Battleaxe', jp:['ドゥームブリンガー'], anim:true, variants:['Red','Blue','Green']},
{c:'Divergence', n:'Divergence Staff', jp:['ダイバージェンス'], anim:true, variants:['Purple','Blue','Green']},
{c:"Dolmir's Revenge", n:"Dolmir's Judgement", jp:['ドルミールズ'], anim:true, variants:['Obsidian','Moss','Ice']},
{c:'Ego', n:'Ego Knife', jpOr:['エゴ ナイフ','エゴナイフ'], variants:['Red','Tan','Pink']},
{c:'Elderflame', n:'Elderflame Dagger', jp:['エルダーフレイム'], vfx:true, variants:[]},
{c:'Emberclad', n:'Emberclad Hammer', jp:['エンバークラッド'], variants:[]},
{c:'Evori Dreamwings', n:"Evori's Spellcaster", jp:['エヴォリズ・スペルキャスター','エヴォリズ'], anim:true, variants:['Pink','Orange','Green']},
{c:'EX.O', n:'EX.O Edge', jp:['EX.O エッジ'], anim:true, variants:['Yellow','Red','Pink']},
{c:'Forsaken', n:'Forsaken Ritual Blade', jp:['フォーセイクン'], vfx:true, variants:[]},
{c:"Fortune's Hand", n:"Fortune's Scepter", jp:['フォーチュンズセプター'], variants:[]},
{c:"Gaia's Vengeance", n:"Gaia's Fury", jp:['ガイアズ・フューリー'], anim:true, variants:['Blue','Green','Orange']},
{c:"Gaia's Wrath", n:"Gaia's Wrath", jp:['ガイアズ・ヴェンジェンス','ガイアズ・ラース'], vfx:true, variants:['Blue','Green','Orange']},
{c:'Glitchpop', n:'Glitchpop Axe', jp:['グリッチポップ','グリッジポップアックス'], anim:true, variants:[]},
{c:'Glitchpop', n:'Glitchpop Dagger', jp:['グリッチポップ ダガー'], vfx:true, variants:[]},
{c:'Gravitational Uranium Neuroblaster', n:'Gravitational Uranium Neuroblaster Baton', jp:['グラビテーショナル・ウラニウム・ニューロブラスター'], anim:true, variants:[]},
{c:'Helix', n:'Helix Daggers', jp:['ヘリックス ダガー'], anim:true, variants:['Gold','Purple','Silver']},
{c:'Holomoku', n:'Kaimana', jp:['カイマナ'], variants:['Deep Sea']},
{c:'Holo Meridian', n:'Holoflare', jp:['ホロフレア'], anim:true, variants:['Yellow','White','Orange']},
{c:'Ignite', n:'Ignite Fan', jp:['イグナイト'], anim:true, variants:['Purple']},
{c:'Intergrade', n:'Intergrade Blade', jp:['インターグレードブレード'], variants:[]},
{c:'Imperium', n:'Blades of Imperium', jp:['ブレード・オブ・インペリウム','インペリウム'], anim:true, variants:['Ruby','Pearl','Obsidian']},
{c:'Ion', n:'Ion Energy Sword', jp:['イオン エナジー ソード'], vfx:true, variants:[]},
{c:'Ion', n:'Ion Karambit', jp:['イオン 2.0','イオン カラムビット'], vfx:true, variants:['Green','Yellow','Blue']},
{c:'Jellybeam', n:'Jellybeam Sugarslice', jp:['ジェリービーム'], variants:[]},
{c:'Kuronami', n:'Kuronami no Yaiba', jp:['クロナミの刃'], anim:true, variants:['Purple','White','Black']},
{c:'Kuronami', n:'Kuronami Naru-Kami', jp:['クロナミ ナルカミ'], anim:true, variants:['Purple','White','Black']},
{c:'Kohaku & Matsuba', n:'Equilibrium', jp:['コウハク','マツバ','イクイリブリウム'], anim:true, variants:['Dark']},
{c:'Luna', n:"Luna's Descent", jp:['ルナ コレクション','ルナ ディセント'], vfx:true, variants:[]},
{c:'Luxe', n:'Luxe Knife', jp:['リュクス'], variants:[]},
{c:'Magepunk', n:'Magepunk Electroblade', jp:['メイジパンク エレクトロブレード'], vfx:true, variants:['Green','Purple','Orange']},
{c:'Magepunk', n:'Magepunk Shock Gauntlet', jp:['メイジパンク ショックガントレット'], vfx:true, variants:['Green','Pink','Orange']},
{c:'Magepunk', n:'Magepunk Sparkswitch', jp:['メイジパンク 3.0','メイジパンク スパークスイッチ'], anim:true, variants:['Green','Black/Red','Yellow']},
{c:'Minima', n:'Minima Karambit', jp:['ミニマ カラムビット'], variants:[]},
{c:'MK.VII Liberty', n:'MK.VII Liberty Combat Knife', jp:['MK.VII リバティー'], variants:['Desert','Sea','Tundra']},
{c:'Mystbloom', n:'Mystbloom Kunai', jp:['ミストブルーム クナイ'], anim:true, variants:['Blue','Orange','Purple']},
{c:'Mystbloom', n:'Mystbloom Fanblade', jp:['ミストブルーム ファンブレイド'], anim:true, variants:['Blue','Orange','Purple']},
{c:'Nanomight', n:'Nanomight Knuckles', jp:['ナノマイト ナックル'], variants:['Green','Blue','Pink']},
{c:'Nebula', n:'Nebula Knife', jp:['ネビュラ'], variants:[]},
{c:'Neo Frontier', n:'Neo Frontier Axe', jp:['ネオフロンティア'], anim:'Transformation', variants:['Gold','Silver','Copper']},
{c:'Neptune', n:'Neptune Anchor', jp:['ネプチューン アンカー'], vfx:true, variants:[]},
{c:'Neptune', n:'Neptune Hook', jp:['ネプチューンフック'], vfx:true, variants:['Black']},
{c:'NO LIMITS', n:'NO LIMITS Bat', jp:['ノーリミット','NO LIMITS'], variants:[]},
{c:'Nocturnum', n:'Nocturnum Scythe', jp:['ノクターナム サイス'], anim:'Transformation', variants:['Black','Blue','Yellow']},
{c:'Nunca Olvidados', n:'Catrina', jp:['カトリーナ','ヌンカ・オルヴィダドス'], variants:['Living','Eternal']},
{c:'Oni', n:'Oni Claw', jp:['オニ クロー'], vfx:true, variants:[]},
{c:'Oni', n:'Onimaru Kunitsuna', jp:['オニ 2.0','鬼丸国綱'], anim:'Sound Effects', variants:['Kumo','Hana','Tsubame']},
{c:'ORA by OneTap', n:'ORA by OneTap Knife', jp:['オラ BY ONETAP'], anim:true, songShuffle:true, variants:[]},
{c:'Origin', n:'Origin Crescent Blade', jp:['オリジン クレセントブレード'], anim:true, variants:[]},
{c:'Orion', n:'Orion Sword', jp:['オリオンソード'], variants:[]},
{c:'Overdrive', n:'Overdrive Blade', jp:['オーバードライブブレード'], anim:true, variants:['Cobalt','Bubblegum','Onyx']},
{c:'Phaseguard', n:'Phaseguard Splitter', jp:['フェーズガード スプリッター'], anim:true, variants:['Black','Blue','Gold']},
{c:'Prelude to Chaos', n:'Blade of Chaos', jp:['プレリュード・トゥー・カオス','ブレード・オブ・カオス'], anim:true, variants:['Green','White','Blue']},
{c:'Prelude to Chaos', n:'Flail of Chaos', jp:['フレイル・オブ・カオス'], anim:true, variants:['Green','White','Blue']},
{c:'Prime', n:'Prime Axe', jp:['プライム コレクション','プライムアックス'], vfx:true, variants:[]},
{c:'Prime//2.0', n:'Prime//2.0 Karambit', jp:['プライム // 2.0'], anim:true, variants:[]},
{c:'Primordium', n:'Blades of Primordia', jp:['ブレード・オブ・プライモーディア'], anim:true, variants:['Venom','Cobalt','Gold']},
{c:'Prism', n:'Prism Knife', jp:['プリズム コレクション','プリズム ナイフ'], variants:[]},
{c:'Protocol 781-A', n:'Personal Administrative Melee Unit', jp:['プロトコル 781-A','パーソナル アドミニスト'], vfx:true, vo:true, variants:['White/Pink','Red/Blue','Green']},
{c:'Radiant Crisis 001', n:'Radiant Crisis 001 Baseball Bat', jp:['レディアントクライシス 001'], vfx:true, variants:[]},
{c:'Radiant Entertainment System', n:'Power Fist', jp:['レディアント・エンターテインメント・システム','パワーフィスト'], anim:true, variants:['Dance Fever','K.nock O.ut!!']},
{c:'Reaver', n:'Reaver Knife', jp:['リーヴァー ナイフ'], vfx:true, variants:[]},
{c:'Reaver', n:'Reaver Karambit', jp:['リーヴァー EP5','リーヴァー EP5 カラムビット'], vfx:true, variants:['Red','Black','White']},
{c:'Reaver', n:'Reaver Butterfly Knife', jp:['リーヴァー バタフライナイフ'], vfx:true, variants:['Red','Black','White']},
{c:'Recon', n:'Recon Balisong', jp:['リコン バリソン'], anim:true, variants:['Red Camo','Blue Camo','Green Camo']},
{c:'Reverie', n:'Reverie Sword', jp:['レヴァリー'], variants:[]},
{c:'RGX 11z Pro', n:'RGX 11z Pro Blade', jp:['RGX 11Z PRO ブレード'], anim:true, variants:['Red','Blue','Yellow']},
{c:'RGX 11z Pro', n:'RGX 11z Pro Firefly', jp:['RGX 11Z PRO 2','ファイアフライ'], anim:'Randomizer', variants:['Red','Blue','Yellow']},
{c:'RGX 11z Pro', n:'RGX 11z Pro Karambit', jp:['RGX 11Z PRO カラムビット'], vfx:true, variants:['Red','Blue','Yellow']},
{c:'Ruination', n:'Blade of the Ruined King', jp:['ルインドキングブレード'], anim:true, variants:['Purple','Red/Yellow','Green']},
{c:'Sarmad', n:'Blade of Serket', jp:['サーマッド','ブレード・オブ・セルケト'], anim:true, variants:[]},
{c:'Sentinels of Light', n:'Relic of the Sentinel', jp:['レリック・オブ・センチネル'], vfx:true, variants:['Pink','Red/Green','Blue/Purple']},
{c:'Sentinels of Light', n:'Relic Stone Daggers', jp:['レリックストーンダガー'], vfx:true, variants:['Pink','Red/Green','Blue/Purple']},
{c:'SilkLeaf', n:'SilkLeaf Fan', jp:['シルクリーフファン'], variants:[]},
{c:'Singularity', n:'Singularity Butterfly Knife', jp:['シンギュラリティー バタフライナイフ'], anim:true, variants:['Red','White','Blue']},
{c:'Singularity', n:'Singularity Knife', jp:['シンギュラリティ コレクション','シンギュラリティ ナイフ'], vfx:true, variants:[]},
{c:'Smite', n:'Smite Knife', jp:['スマイト ナイフ'], variants:[]},
{c:'Smite', n:'Smite Hammer', jp:['スマイト ハンマー'], variants:[]},
{c:'Snowfall', n:'Snowfall Wand', jp:['スノーフォール'], variants:[]},
{c:'Solarstride', n:'Solarstride Flamethrower', jp:['ソーラーストライド'], anim:true, variants:['Blue','White','Black']},
{c:'Soulstrife', n:'Soulstrife Scythe', jp:['ソウルストライフ'], vfx:true, variants:[]},
{c:'Sovereign', n:'Sovereign Sword', jp:['ソヴリン コレクション','ソヴリン ソード'], vfx:true, variants:[]},
{c:'Sovereign', n:'Eternal Sovereign', jp:['エターナル ソヴリン'], vfx:true, variants:['Green','Teal','Red']},
{c:'Storm Maw', n:'Storm Maw Axe', jp:['ストームモウアックス'], variants:[]},
{c:'Switchback', n:'Switchback Ascender', jp:['スイッチバック'], variants:[]},
{c:'Spectrum', n:'Waveform', jp:['ウェーブフォーム'], vfx:true, variants:['Black','Red','Purple/Pink']},
{c:'SplashX', n:'SplashX Gloves', jp:['スプラッシュXグローブ'], anim:true, variants:['Black','White','Purple']},
{c:'Spline', n:'Spline Dagger', jp:['スプライン ダガー'], variants:[]},
{c:'Tethered Realms', n:'Prosperity', jp:['プロスペリティ'], anim:true, variants:[]},
{c:'Tigris', n:'Hu Else', jp:['ティグリス','虎刀'], variants:[]},
{c:'Titanmail', n:'Titanmail Mace', jp:['チタンメイル'], anim:true, variants:[]},
{c:'Undercity', n:'Hack', jp:['アンダーシティ','ハック'], anim:true, variants:[]},
{c:'Valiant Hero', n:'Ruyi Staff', jp:['如意棒'], anim:true, variants:['Sunset','Dusk','Night']},
{c:'VALORANT GO! Vol. 1', n:'VALORANT GO! Vol. 1 Knife', jp:['VALORANT GO! VOL.1'], anim:true, variants:[]},
{c:'VALORANT GO! Vol. 2', n:"Yoru's Stylish Butterfly Comb", jp:['ヨルのイケてるバタフライコーム'], anim:true, variants:[]},
{c:'VALORANT GO! Vol. 3', n:'VALORANT GO! Vol. 3 Dagger', jp:['VALORANT GO! VOL.3'], variants:[]},
{c:'VCT 2025 Season', n:'VCT 2025 Karambit', jp:['VCT 2025 カラムビット'], vfx:true, aura:true, variants:['CN','Pacific','Americas','EMEA']},
{c:'VCT 2026 Season', n:'VCT 2026 Sigil', jp:['VCT 2026 シジル'], anim:'Sound Effects', aura:true, variants:['CN','Pacific','Americas','EMEA']},
{c:'VCT LOCK//IN', n:'VCT LOCK//IN Misericórdia', jp:['VCT LOCK//IN','ミゼリコルディア'], anim:true, aura:true, variants:['Pacific','Americas','EMEA']},
{c:'Wasteland', n:'Wasteland Crowbar', jp:['ウェイストランド'], variants:[]},
{c:'Winterwunderland', n:'Winterwunderland Candy Cane', jp:['ウィンターワンダーランド','キャンディーステッキ'], variants:['Green','Blue','Rainbow']},
{c:'Wonderstallion', n:'Wonderstallion Hammer', jp:['ワンダースタリオン'], anim:true, variants:[]},
{c:'Xenohunter', n:'Xenohunter Knife', jp:['ゼノハンター'], anim:true, variants:[]},
{c:'XERØFANG', n:'XERØFANG Knife', jp:['ゼロファングナイフ'], anim:true, variants:['Black','Pink','Silver']},
];

const BATTLEPASS = [
{c:'.SYS', n:'.SYS Melee', act:'Ep 04 Act 3', jp:['.SYS'], variants:[]},
{c:'Artisan', n:'Artisan Foil', act:'Ep 03 Act 2', jp:['アルティザン フルーレ'], variants:['Red','Green','Blue']},
{c:'ATLAS // CMD', n:'ATLAS // CMD Baton', act:'V25 Act 4', jp:['ATLAS'], variants:[]},
{c:'Bound', n:'Bound', act:'Ep 06 Act 3', jp:['バウンド'], variants:[]},
{c:'Bubble Pop', n:'Bubble Pop Light Stick', act:'Ep 09 Act 1', jp:['バブルポップ'], variants:['Red']},
{c:'Byteshift', n:'Byteshift Knife', act:'V25 Act 2', jp:['バイトシフト'], variants:['Purple','Red','Yellow']},
{c:'Comet', n:'Comet Sword', act:'Ep 08 Act 3', jp:['コメット ソード'], variants:['Red','Pink','Yellow']},
{c:'Composite', n:'Composite Knife', act:'Ep 07 Act 1', jp:['コンポジット'], variants:[]},
{c:'Genesis', n:'Genesis Arc', act:'Ep 03 Act 3', jp:['ジェネシス アーク'], variants:[]},
{c:'Guardrail', n:'Guardrail Hammer', act:'Ep 08 Act 1', jp:['ガードレール'], variants:[]},
{c:'Heartstopper', n:'Heart Splitter', act:'V25 Act 6', jpOr:['ハートスプリッター','ハートストッパー'], variants:['Black','Blue']},
{c:'Hieroscape', n:'Hieroscape Blades', act:'V25 Act 1', jp:['ヒエロスケープ'], variants:[]},
{c:'Hivemind', n:'Hivemind Sword', act:'Ep 01 Act 2', jp:['ハイヴマインド'], variants:[]},
{c:'Interhelm', n:'Interhelm Sword', act:'V25 Act 5', jp:['インターヘルム'], variants:['Blue','Green','Purple']},
{c:'Iridian Thorn', n:'Iridian Thorn Blade', act:'Ep 05 Act 3', jp:['イリディアンソーン'], variants:[]},
{c:'K/TAC', n:'K/TAC Blade', act:'Ep 03 Act 1', jp:['K/TAC'], variants:[]},
{c:'Keys to Elysium', n:'Keys to Elysium', act:'V26 Act 3', jp:['キーズ・トゥ・エリジウム'], variants:['Green','Red','Purple']},
{c:'Kingdom', n:'Kingdom Knife', act:'Ep 01 Act 1', jp:['キングダム'], variants:[]},
{c:'Montage', n:'Montage Axe', act:'V26 Act 1', jp:['モンタージュ'], variants:['Pink','Purple']},
{c:'Paceline', n:"Paceline's Edge", act:'V26 Act 2', jp:['ペースライン'], variants:[]},
{c:'Outpost', n:'Outpost Melee', act:'Ep 02 Act 1', jp:['アウトポスト'], variants:[]},
{c:'Overlay', n:'Overlay Dagger', act:'Ep 09 Act 2', jp:['オーバーレイ'], variants:['Black','Pink','Grey']},
{c:'Piedra del Sol', n:'Obsidiana', act:'Ep 05 Act 2', jp:['ピエドラ・デル・ソル','オブシディアナ'], variants:[]},
{c:'Prism III', n:'Prism III Axe', act:'Ep 02 Act 2', jpOr:['プリズム Ⅲ','プリズム3','プリズムIII','プリズム III'], variants:['Pink','Green','Purple']},
{c:'Ruin', n:'Ruin Dagger', act:'Ep 01 Act 3', jp:['ルイン ダガー'], variants:[]},
{c:'Sandswept', n:'Sandswept Dagger', act:'Ep 07 Act 3', jp:['サンドスウェプト'], variants:['Ivory','Indigo','Scarlet']},
{c:'Shellspire', n:'Shellspire Sword', act:'Ep 08 Act 2', jp:['シェルスパイア'], variants:[]},
{c:'Solarex', n:'Solarex Relic', act:'V25 Act 3', jpOr:['ソーラレックス','ソーラエックス','ソーラーレックス','ソーラーエックス'], variants:['Yellow','Green','Purple']},
{c:'Songsteel', n:'Songsteel', act:'Ep 02 Act 3', jp:['ソングスティール'], variants:[]},
{c:'Striker', n:'Striker Knife', act:'Ep 04 Act 2', jp:['ストライカー'], variants:['Green/Yellow/Black','Pink/Teal/Purple','Blue/White/Red']},
{c:'Task Force 809', n:'Task Force 809 Knife', act:'Ep 05 Act 1', jp:['タスクフォース'], variants:[]},
{c:'Transition', n:'Transition Knife', act:'Ep 07 Act 2', jpOr:['トラジションナイフ','トランジション'], variants:['Blue','Orange','Green']},
{c:'Tilde', n:'Tilde Knife', act:'Ep 06 Act 2', jp:['ティルデ'], variants:['Red','Purple','Green']},
{c:'Torque', n:'Torque Coiler', act:'Ep 09 Act 3', jp:['トルクコイラー'], variants:['Yellow','Blue','Orange']},
{c:'Velocity', n:'Velocity Karambit', act:'Ep 04 Act 1', jp:['ヴェロシティー'], variants:['Yellow','Purple','Aquamarine']},
{c:'Venturi', n:'Venturi Knife', act:'Ep 06 Act 1', jp:['ヴェンチュ'], variants:[]},
];

// Collections the Wiki marks with "*": limited-time weapon skins that never appear in the
// Store's daily rotation (Champions/VCT capsule knives, anniversary/collab exclusives, etc.).
const LIMITED_COLLECTIONS = new Set([
  '5 Years // Beta Remastered', 'Arcane', 'Champions 2021', 'Champions 2022',
  'Champions 2023', 'Champions 2024', 'Champions 2025', 'Ignite',
  'VCT 2025 Season', 'VCT 2026 Season', 'VCT LOCK//IN',
]);

module.exports = { STORE, BATTLEPASS, jpColor, LIMITED_COLLECTIONS, COLOR_JP };
